# Use extension "REST Client" to request APIs
### Setup Testing
GET http://localhost:3000/

### 404 testing 
GET http://localhost:3000/jpt

############# USER RELATED #####################
### Get users
GET http://localhost:3000/users

### Get a user
GET http://localhost:3000/user/68

### login
POST http://localhost:3000/login
Content-Type: application/json

{
  "identifier": "9800000009",
  "password": "pw"
}


### Signup
POST http://localhost:3000/signup
Content-Type: application/json

{
  "name": "suwi",
  "location_latitude": 45,
  "location_longitude": 45,
  "email": "sth2@ath.com",
  "phone": 9841123464,
  "password": "pw"
}

### Update User
PUT http://localhost:3000/updateUser/68
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="name"

Nabin Sah
--boundary
Content-Disposition: form-data; name="location_latitude"

27.7172
--boundary
Content-Disposition: form-data; name="location_longitude"

85.3240
--boundary
Content-Disposition: form-data; name="email"

nabindada@homesolution.com
--boundary
Content-Disposition: form-data; name="phone"

9800000068
--boundary
Content-Disposition: form-data; name="password"

pw
--boundary
Content-Disposition: form-data; name="profile_picture"; filename="profile.jpg"
Content-Type: image/jpeg

< ./C:/Users/USER/OneDrive/Pictures/photos-2191/Photos/FB_IMG_15586343730679352.jpg
--boundary--






############ SERVICE PROVIDERS RELATED ##

### Get Service Providers
GET http://localhost:3000/providers

################### SERVICE RELATED ############

### Create service
POST http://localhost:3000/createService
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="spid"

4
--boundary
Content-Disposition: form-data; name="name"

Vivek Electronics
--boundary
Content-Disposition: form-data; name="description"

This is one of the best electronics service available in Pokhara.
--boundary
Content-Disposition: form-data; name="type"

Electronics
--boundary
Content-Disposition: form-data; name="mincharge"

150
--boundary
Content-Disposition: form-data; name="profile_picture"; filename="FB_IMG_15586343730679352.jpg"
Content-Type: image/jpeg

< ./C:/Users/USER/OneDrive/Pictures/photos-2191/Photos/FB_IMG_15586343730679352.jpg
--boundary--


### Get services
GET http://localhost:3000/services
Content-Type: application/json

{
  #"type": "Electronics"
  # pass type to gwt services of a particular type else you will get all the services.
}
### Get a service
GET http://localhost:3000/service/3   # Pass service ID

### Get service types or categories
GET http://localhost:3000/serviceCategories

### Delete a service
DELETE http://localhost:3000/deleteService/2 # pass sid (service id)

### Update service
PUT http://localhost:3000/updateService
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="sid"

4
--boundary
Content-Disposition: form-data; name="name"

Vivek Electronics Updated
--boundary--







################# CONTACT RELATED #########
### Call (get phone number)
GET http://localhost:3000/call
Content-Type: application/json

{
  "id": 69
  # send either id or spid only
}

### Message
POST http://localhost:3000/message
Content-Type: application/json

{
  "id": 69,
  "spid": 4,
  "messagetext": "Hi dear customer...",
  "senderType": "provider"
  # senderType must be either "user" or "provider"
}

### Get Chats
GET http://localhost:3000/chat
Content-Type: application/json

{
  "id": 69,
  "spid": 4
}




############### BOOKING RELATED #######
### Book a service // Send request with JWT token to book a service.
POST http://localhost:3000/booking
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoic3RoNjhAYXRoLmNvbSIsImlhdCI6MTczMjg2ODQ1MCwiZXhwIjoxNzMyOTU0ODUwfQ.HC0WofOVno1yyQWL5n9lQ0L7f5dtvX4H1mAWaB1GBeM
Content-Type: application/json

{
  "id": 32,
  #id = user id 
  "sid": 4,
  #sid = service id
  "status": "pending"
}

### Get booking
GET http://localhost:3000/getBooking
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoic3RoNjhAYXRoLmNvbSIsImlhdCI6MTczMjg2ODU5OCwiZXhwIjoxNzMyOTU0OTk4fQ.Kk1eNZ_jk5Hbb8ACZzeyTt8qZQX4r6foJsG6i9GVqHA
Content-Type: application/json

{
  "id": 32
  #"sid": 4
}

### Update booking status
PUT http://localhost:3000/updateStatus
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoic3RoNjhAYXRoLmNvbSIsImlhdCI6MTczMjg2ODU5OCwiZXhwIjoxNzMyOTU0OTk4fQ.Kk1eNZ_jk5Hbb8ACZzeyTt8qZQX4r6foJsG6i9GVqHA
Content-Type: application/json

{
  "bid": 1,
  "status": "approved"
}
